### ISSUE TITLE
Add characters before saving custom profile

### ISSUE THREAD

**Issue by shuvashish76** [ljmc2000/NoiseLooper#3]
Currently if you add nothing in the box & just click save, it adds a profile with no name which looks very odd to me. I think it would be better to accept creating profile only if something is added texts, numbers, symbols etc. (excluding empty space in 1st character)
If nothing added in the box OK button should function as cancel.

**Comment by ljmc2000** [comment]
As of attached pull request, the okay button is only shown if the profile name is valid (ie matches the regular expression `\s*(.*[\S])\s*`)
