### ISSUE TITLE
Request: Sleep Timer

### ISSUE THREAD

**Issue by roy-heinrich** [ljmc2000/NoiseLooper#4]
A sleep timer would be a nice feature if some people use this app for sleeping. It should automatically stop playing according to the time that the user set it to.

**Comment by ljmc2000** [comment]
![Screenshot_20240320_000935](https://github.com/ljmc2000/NoiseLooper/assets/14955891/e842e6a8-fe7f-489d-9202-38e39205d5d2)
![Screenshot_20240320_000957](https://github.com/ljmc2000/NoiseLooper/assets/14955891/36398bcc-be7d-486f-b8f7-c688e3495d8e)

Would it make more sense to enter a time to stop (first image), or a time until stop (second image)?

Personally I'm thinking time until stop, but if you have a preference please make it clear here.

**Comment by roy-heinrich** [comment]
I think the time until stop (second image) would appear more logical here as it would give the user a more easy approach to until when they would like to hear the ambiance noises.

**Comment by ljmc2000** [comment]
![Screenshot_20240321_014653](https://github.com/ljmc2000/NoiseLooper/assets/14955891/69cacdc4-d9be-4b55-a3df-c19c6fbf1abd)

final design
